### ISSUE TITLE
Loading fails at runtime in Mingw64 + pc-windows-gnu toolchain

### ISSUE THREAD

**Issue by norru** [mjkoo/epoxy-rs#7]
Hi,

I have successfully managed to build on mingw64 with `x86_64-pc-windows-gnu`, however my code (which would otherwise work fine in `x86_64-*-linux-gnu`) fails at runtime, with lots of loading failures.

```
epoxy_glAccum: "The specified procedure could not be found. (os error 127)"
epoxy_glActiveShaderProgram: "The specified procedure could not be found. (os error 127)"
epoxy_glActiveTexture: "The specified procedure could not be found. (os error 127)"
epoxy_glAlphaFunc: "The specified procedure could not be found. (os error 127)"
epoxy_glAreTexturesResident: "The specified procedure could not be found. (os error 127)"
epoxy_glArrayElement: "The specified procedure could not be found. (os error 127)"
epoxy_glAttachObjectARB: "The specified procedure could not be found. (os error 127)"
...
```

Affected code is at https://github.com/itadinanta/gfx-gtk/blob/master/src/lib.rs#L148.

Any clue on how I could track it down (on Windows 10 + mingw?)

Cheers
Nico

**Comment by norru** [comment]
https://users.rust-lang.org/t/exporting-dynamic-symbols-from-executable/6103

**Comment by norru** [comment]
https://stackoverflow.com/questions/46032713/is-there-some-way-that-rust-cargo-put-dll-file-into-exe-program

**Comment by norru** [comment]
Here's the fix for Windows. In `mingw64`, libepoxy is linked dynamically:
```rust
fn dynamic_library_get_proc_addr(s: &str) -> *const std::ffi::c_void {
	unsafe {
		match shared_library::dynamic_library::DynamicLibrary::open(Some(&Path::new("libepoxy-0.dll")))
			.unwrap()
			.symbol(s)
		{
			Ok(v) => v,
			Err(e) => {
				println!("{:?}", e);
				ptr::null()
			}
		}
	}
}
```

**Comment by mjkoo** [comment]
@norru Thanks for looking into this. I see you closed the issue, glad you were able to resolve your problem!

Is the code you commented generally useful / should be merged? If so, a PR would be appreciated :)

*Edit:* I see this is in code from a client application, perhaps it will be useful to have defaults for different configurations guarded behind `#cfg` flags in future :thinking: It's been a while since I've looked into this

**Comment by norru** [comment]
I'll see if I can come up with something useful to share, otherwise just having this workaround in the wild could save other fellow rustaceans many a headache :)

**Comment by norru** [comment]
And yes, I have closed the issue as it's application code rather than library code.

**Comment by norru** [comment]
I've managed to tidy it up a bit by implementing a failover system which should not need `#cfg` bracketing, need to test across a few systems:

```rust
pub fn load() {
	use self::dl::{epoxy_get_proc_addr, fn_from, DlProcLoader, Failover};
	let loader = Failover(
		DlProcLoader::current_module(),
		Failover(
			DlProcLoader::open(Path::new("libepoxy-0")),
			Failover(
				DlProcLoader::open(Path::new("libepoxy0")),
				DlProcLoader::open(Path::new("libepoxy")),
			),
		),
	);
	epoxy::load_with(fn_from(loader));
	gl::load_with(epoxy_get_proc_addr);
}
```

Perhaps I could move the `DlProcLoader` and `Failover` code across to Epoxy?

https://github.com/itadinanta/gfx-gtk/blob/feature/epoxy_dll/src/dl.rs

**Comment by norru** [comment]
I've tested this on Devuan and Windows 10, seems fine, doesn't requires `#cfg[]`
